# Generated by Django 6.0.3 on 2026-03-16 21:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactQuery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Turf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=300)),
                ('price_per_hour', models.DecimalField(decimal_places=2, max_digits=8)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='turf_images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time_slot', models.CharField(choices=[('06:00-07:00', '6:00 AM – 7:00 AM'), ('07:00-08:00', '7:00 AM – 8:00 AM'), ('08:00-09:00', '8:00 AM – 9:00 AM'), ('09:00-10:00', '9:00 AM – 10:00 AM'), ('10:00-11:00', '10:00 AM – 11:00 AM'), ('11:00-12:00', '11:00 AM – 12:00 PM'), ('12:00-13:00', '12:00 PM – 1:00 PM'), ('13:00-14:00', '1:00 PM – 2:00 PM'), ('14:00-15:00', '2:00 PM – 3:00 PM'), ('15:00-16:00', '3:00 PM – 4:00 PM'), ('16:00-17:00', '4:00 PM – 5:00 PM'), ('17:00-18:00', '5:00 PM – 6:00 PM'), ('18:00-19:00', '6:00 PM – 7:00 PM'), ('19:00-20:00', '7:00 PM – 8:00 PM'), ('20:00-21:00', '8:00 PM – 9:00 PM'), ('21:00-22:00', '9:00 PM – 10:00 PM')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to=settings.AUTH_USER_MODEL)),
                ('turf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='turf_app.turf')),
            ],
            options={
                'unique_together': {('turf', 'date', 'time_slot')},
            },
        ),
    ]
